name: Fetch NASA FIRMS data

on:
  schedule:
    - cron: "0 * * * *"  # toutes les heures
  workflow_dispatch:

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install pandas geopandas scikit-learn shapely requests tqdm

      - name: Run script
        env:
          NASA_FIRMS_API_KEY: ${{ secrets.NASA_FIRMS_API_KEY }}
        run: python script_nasa.py
